### ISSUE TITLE
Error when make

### ISSUE THREAD

**Issue by petrmatula190** [buzzert/capswheel#1]
I tried install, because this is perfect idea. I install all requirements on Ubuntu 18.04 and still get this error:
```
matlala@gpdpocket2 ~/capswheel $ make
cc    -c -o capswheel.o capswheel.c
capswheel.c: In function ‘send_wheel_event’:
capswheel.c:58:27: error: ‘REL_WHEEL_HI_RES’ undeclared (first use in this function); did you mean ‘REL_WHEEL’?
     uint16_t hires_code = REL_WHEEL_HI_RES;
                           ^~~~~~~~~~~~~~~~
                           REL_WHEEL
capswheel.c:58:27: note: each undeclared identifier is reported only once for each function it appears in
capswheel.c:61:22: error: ‘REL_HWHEEL_HI_RES’ undeclared (first use in this function); did you mean ‘REL_WHEEL_HI_RES’?
         hires_code = REL_HWHEEL_HI_RES;
                      ^~~~~~~~~~~~~~~~~
                      REL_WHEEL_HI_RES
<vestavěný>: recipe for target 'capswheel.o' failed
make: *** [capswheel.o] Error 1
```

**Comment by buzzert** [comment]
Sorry I missed this. I'm surprised that definition is missing on Ubuntu. Can you try replacing `REL_WHEEL_HI_RES` with `REL_WHEEL`?

**Comment by petrmatula190** [comment]
Thanks, I tried compile on virtualized Ubuntu 19.04 (I used it like main version on GPD Pocket 2, because HiDPI and touch experience with newest gnome is absolutely better). On 19,04 I have not any problem.

On 18.04, replacing work for compile.

I will try real compile and usage it on GPD when i will home on evening.

**Comment by petrmatula190** [comment]
So, make works on 18.04, but systemd service have error in exec:
```
matlala@gpdpocket2 ~/capswheel $ systemctl status capswheel
● capswheel.service - Activate caps lock to scroll
   Loaded: error (Reason: Exec format error)
   Active: inactive (dead)
```
But devices specify correct in service
```
matlala@gpdpocket2 ~/capswheel $ ls /dev/input/by-id
usb-HAILUCK_CO._LTD_USB_KEYBOARD-event-if01  usb-HAILUCK_CO._LTD_USB_KEYBOARD-if01-event-mouse
usb-HAILUCK_CO._LTD_USB_KEYBOARD-event-kbd   usb-HAILUCK_CO._LTD_USB_KEYBOARD-if01-mouse
```
EDIT:I tried start manually and found some problem with libevdev (after chmod 777 to keyboard and mouse)
`sudo intercept -g /dev/input/by-id/usb-HAILUCK_CO._LTD_USB_KEYBOARD-if01-event-mouse | /usr/local/bin/capswheel /dev/input/by-id/usb-HAILUCK_CO._LTD_USB_KEYBOARD-event-kbd | uinput -d /dev/input/by-id/usb-HAILUCK_CO._LTD_USB_KEYBOARD-if01-event-mouse
libevdev_uinput_create_from_device failed: Permission denied
`


But on 19.04 works perfect :-)

**Comment by petrmatula190** [comment]
So I found reason. Error is not in your code, but in dependency to libevdev-dev while compile interception-tools. In Ubuntu 18.04 have older libevdev-dev 1.5.8+dfsg-1 than 19.04 (version 1.6.0+dfsg-1).

REL_WHEEL_HI_RES and REL_HWHEEL_HI_RES is availabble should be from version 1.5.9 or 1.6.

I tried update libevdev-dev, but there is too mutch dependecies up to gcc and more. 
Finally, please add warning to README. For me is more importation 19.04 and newest Ubuntu releases.
